# Pakistani-specific data based on actual bill
PAKISTANI_NAMES = [
    'Abdul Rehman','Abdul Hadi','Abdul Samad','Abdul Wahab','Abdul Basit','Abdul Qadir',
    'Abdul Rafay','Abdul Moiz','Abdul Subhan','Abdul Ahad','Abdul Sami','Abdul Rehman Khan',
    'Abdul Jabbar','Abdul Hannan','Abdul Raheem','Abdul Kareem','Abdul Mannan',
    'Abdul Sattar','Abdul Majid','Abdul Aziz','Abdul Qayyum','Abdul Latif',
    'Abdul Ghani','Abdul Hameed','Abdul Rauf','Abdul Malik','Abdul Majeed',
    'Abdullah','Ali','Ahmed','Ahmad','Ahsan','Adeel','Adnan','Afaq','Aamir','Ammar',
    'Anas','Arham','Arslan','Arsalan','Asad','Asim','Atif','Atiq','Awais','Azhar',
    'Azlan','Azam','Babar','Bilal','Danish','Dawood','Ehsan','Fahad','Faizan','Faisal',
    'Farhan','Faraz','Fawad','Furqan','Hafiz','Hamza','Haris','Hassan','Haseeb','Hasnain',
    'Hashir','Hammad','Haseeb','Hassan Raza','Hassan Ali','Hassan Ahmed',
    'Imran','Irfan','Ismail','Ilyas','Junaid','Kashif','Kamran','Khurram','Majid',
    'Mansoor','Mudassir','Mustafa','Nabeel','Naveed','Noman','Owais','Qasim','Rafay',
    'Rashid','Raza','Rehan','Rizwan','Saad','Sajid','Salman','Sameer','Sami',
    'Saqib','Shahbaz','Shahzaib','Shahzad','Shehryar','Sheryar','Shahid','Shakir',
    'Sharjeel','Shayan','Sohaib','Sohail','Subhan','Sufyan','Talha','Tariq',
    'Tayyab','Umair','Usama','Usman','Waqas','Yasir','Yousaf','Yousuf','Zahid',
    'Zain','Zain Ali','Zain Ahmed','Zeeshan','Zohaib','Zubair',
    'Aaliyah','Aiman','Aiza','Aleena','Alina','Alishba','Aliza','Amna','Anaya','Anum',
    'Aqsa','Areeba','Arooj','Arisha','Asma','Ayesha','Aiza Noor','Benish','Bushra',
    'Dua','Eman','Fatima','Fatima Noor','Fiza','Hafsa','Hania','Hiba','Hina',
    'Hoor','Iqra','Khadija','Kiran','Laiba','Lubna','Mahnoor','Mahira','Maira',
    'Maria','Maryam','Mehwish','Minal','Mishal','Nadia','Naila','Nimra','Noor',
    'Rabia','Ramsha','Rania','Rida','Rimsha','Saba','Sadia','Sahar','Saima',
    'Sakina','Saman','Sana','Sania','Sarah','Sidra','Sobia','Sonia','Sumaiya',
    'Syeda','Tehreem','Uzma','Wania','Yasmin','Yumna','Zainab','Zara','Zarmeen',
    'Zoya','Zunaira','Zoya Fatima','Hoorain','Eshal','Inaya','Abeer','Hajra',
    'Komal','Maham','Maliha','Sehrish','Tooba','Wajiha','Yusra','Zoya Khan',
    'Zainab Fatima','Aiman Khan','Aisha Noor','Areej','Arfa','Bisam','Hooria',
    'Kainat','Mahira Khan','Noreen','Rabail','Rameen','Sabeen','Tania','Zimal',
    'Ahmed Khan','Ali Khan','Usman Khan','Bilal Khan','Hassan Khan','Imran Khan',
    'Farhan Khan','Zeeshan Khan','Saad Khan','Talha Khan','Rehan Khan','Sohail Khan',
    'Qasim Khan','Arslan Khan','Kamran Khan','Rizwan Khan','Naveed Khan',
    'Faisal Khan','Adeel Khan','Junaid Khan',
    'Ahmed Malik','Ali Malik','Usman Malik','Bilal Malik','Hassan Malik',
    'Imran Malik','Farhan Malik','Zeeshan Malik','Saad Malik','Talha Malik',
    'Ahmed Butt','Ali Butt','Usman Butt','Bilal Butt','Hassan Butt',
    'Imran Butt','Farhan Butt','Zeeshan Butt','Saad Butt','Talha Butt',
    'Ahmed Chaudhry','Ali Chaudhry','Usman Chaudhry','Bilal Chaudhry',
    'Hassan Chaudhry','Imran Chaudhry','Farhan Chaudhry',
    'Ahmed Sheikh','Ali Sheikh','Usman Sheikh','Bilal Sheikh',
    'Hassan Sheikh','Imran Sheikh','Farhan Sheikh',
    'Ahmed Qureshi','Ali Qureshi','Usman Qureshi','Bilal Qureshi',
    'Hassan Qureshi','Imran Qureshi','Farhan Qureshi',
    'Ahmed Siddiqui','Ali Siddiqui','Usman Siddiqui','Bilal Siddiqui',
    'Hassan Siddiqui','Imran Siddiqui','Farhan Siddiqui',
    'Ahmed Abbasi','Ali Abbasi','Usman Abbasi','Bilal Abbasi',
    'Hassan Abbasi','Imran Abbasi','Farhan Abbasi',
    'Abbas','Afaq Ahmed','Ahsan Raza','Akbar Ali','Akram Khan','Altaf Hussain',
    'Amanullah','Amjad Ali','Anwar Hussain','Arif Mehmood','Ashfaq Ahmed',
    'Asif Ali','Ataullah','Aziz Ullah','Bashir Ahmed','Chaudhry Nadeem',
    'Dilawar Hussain','Ejaz Ahmed','Fakhar Zaman','Ghulam Mustafa',
    'Ghulam Rasool','Habib Ullah','Hafeez Ahmed','Hamid Raza',
    'Haq Nawaz','Ijaz Ahmed','Ikram Ullah','Inam Ullah','Ishaq Khan',
    'Jahangir Khan','Javed Iqbal','Khalid Mehmood','Liaqat Ali',
    'Mohsin Raza','Mukhtar Ahmed','Munir Ahmed','Nadeem Ahmed',
    'Nasir Mehmood','Nisar Ahmed','Pervez Akhtar','Rafaqat Ali',
    'Rasheed Ahmed','Shabbir Ahmed','Shafqat Ali','Shoaib Akhtar',
    'Sikandar Hayat','Tanveer Ahmed','Waheed Ahmed','Zafar Iqbal',
    'Zulfiqar Ali', 'Asad Satti',
]

FATHER_NAMES = [
    'Abdul Rehman','Abdul Rahman','Abdul Hameed','Abdul Qadir','Abdul Karim',
    'Abdul Latif','Abdul Majid','Abdul Ghafoor','Abdul Sattar','Abdul Rasheed',
    'Abdul Wahid','Abdul Waheed','Abdul Hannan','Abdul Jabbar','Abdul Samad',
    'Abdul Rauf','Abdul Basit','Abdul Shakoor','Abdul Majeed','Abdul Ghani',
    'Abdul Malik','Abdul Qayyum','Abdul Manan','Abdul Haleem','Abdul Bari',
    'Abdul Subhan','Abdul Razzaq','Abdul Haq','Abdul Salam','Abdul Qudoos',
    'Abdul Ahad','Abdul Sami','Abdul Muqeet','Abdul Mateen','Abdul Jabir',
    'Muhammad Ashraf','Muhammad Iqbal','Muhammad Anwar','Muhammad Akram',
    'Muhammad Younis','Muhammad Hanif','Muhammad Shafiq','Muhammad Arif',
    'Muhammad Bashir','Muhammad Idrees','Muhammad Latif','Muhammad Afzal',
    'Muhammad Aslam','Muhammad Rafiq','Muhammad Tariq','Muhammad Nawaz',
    'Muhammad Yaqoob','Muhammad Saleem','Muhammad Khalid','Muhammad Zubair',
    'Muhammad Ramzan','Muhammad Ameen','Muhammad Ismail','Muhammad Sharif',
    'Muhammad Ayub','Muhammad Sarwar','Muhammad Siddique','Muhammad Shabbir',
    'Muhammad Maqsood','Muhammad Saeed','Muhammad Hanif Khan',
    'Muhammad Ashraf Malik','Muhammad Iqbal Chaudhry','Muhammad Akhtar Hussain',
    'Rashid Ahmed','Rasheed Ahmed','Shahid Mehmood','Shahid Iqbal',
    'Zafar Iqbal','Tanveer Ahmed','Nazar Hussain','Naseer Ahmed',
    'Shabbir Ahmed','Mukhtar Ahmed','Munir Ahmed','Javed Iqbal',
    'Javed Akhtar','Pervez Akhtar','Pervez Iqbal','Rafaqat Ali',
    'Ghulam Mustafa','Ghulam Rasool','Ghulam Murtaza','Ghulam Haider',
    'Ghulam Abbas','Ghulam Akbar','Manzoor Hussain','Mazhar Hussain',
    'Zulfiqar Ali','Liaqat Ali','Riaz Ahmed','Riyaz Ahmed',
    'Saeed Ahmed','Sajjad Hussain','Ijaz Ahmed','Ejaz Ahmed',
    'Asghar Ali','Akhtar Hussain','Ashfaq Ahmed','Arshad Mehmood',
    'Arif Mehmood','Arif Hussain','Aftab Ahmed','Ameer Hamza', 'Asif Satti',
    'Allah Ditta','Allah Bakhsh','Bashir Ahmed','Barkat Ali',
    'Basharat Ali','Haq Nawaz','Inayat Ullah','Ikram Ullah',
    'Khuda Bakhsh','Mehar Din','Noor Din','Peer Bakhsh',
    'Shafqat Ali','Shaukat Ali','Sharafat Ali','Sikandar Hayat',
    'Sultan Mehmood','Taj Din','Wazir Ahmed','Zaman Khan',
    'Rahim Khan','Karim Khan','Salim Khan','Aziz Khan','Latif Khan',
    'Yousaf Khan','Hameed Khan','Waheed Khan','Naeem Khan',
    'Rafiq Khan','Jahangir Khan','Nawaz Khan','Anwar Khan',
    'Akbar Khan','Aslam Khan','Ashraf Khan','Zahid Khan',
    'Sabir Khan','Fazal Khan','Qadir Khan',
    'Rashid Malik','Akram Malik','Hanif Malik','Younas Malik',
    'Aslam Malik','Bashir Malik','Tariq Malik','Ashfaq Malik',
    'Nadeem Malik','Saeed Malik','Farooq Malik','Rafiq Malik',
    'Rashid Chaudhry','Akram Chaudhry','Hanif Chaudhry',
    'Younas Chaudhry','Aslam Chaudhry','Bashir Chaudhry',
    'Tariq Chaudhry','Ashfaq Chaudhry','Nadeem Chaudhry',
    'Rashid Butt','Akram Butt','Hanif Butt',
    'Younas Butt','Aslam Butt','Bashir Butt',
    'Tariq Butt','Ashfaq Butt','Nadeem Butt',
    'Rashid Qureshi','Akram Qureshi','Hanif Qureshi',
    'Younas Qureshi','Aslam Qureshi','Bashir Qureshi',
    'Tariq Qureshi','Ashfaq Qureshi','Nadeem Qureshi',
    'Rashid Abbasi','Akram Abbasi','Hanif Abbasi',
    'Younas Abbasi','Aslam Abbasi','Bashir Abbasi',
    'Tariq Abbasi','Ashfaq Abbasi','Nadeem Abbasi',
    'Rashid Sheikh','Akram Sheikh','Hanif Sheikh',
    'Younas Sheikh','Aslam Sheikh','Bashir Sheikh',
    'Tariq Sheikh','Ashfaq Sheikh','Nadeem Sheikh',
    'Fazal Rehman','Fazlur Rehman','Atta Ullah','Ata ur Rehman',
    'Abid Hussain','Abid Ali','Amin Ullah','Amir Hussain',
    'Anis Ahmed','Aqeel Ahmed','Asif Mehmood','Azhar Hussain',
    'Babar Hussain','Dilawar Hussain','Fida Hussain',
    'Ghulam Nabi','Habib Ullah','Hafeez Ullah',
    'Hameed Ullah','Imdad Hussain','Imtiaz Ahmed',
    'Israr Ahmed','Jamil Ahmed','Jamshed Iqbal',
    'Khalid Mehmood','Khizar Hayat','Mahmood Ahmed',
    'Masood Ahmed','Mehmood Hussain','Mian Iqbal',
    'Mohsin Ali','Mumtaz Ahmed','Nadeem Ahmed',
    'Nasir Hussain','Nisar Ahmed','Parvez Ahmed',
    'Qamar Abbas','Qazi Ahmed','Rafique Ahmed',
    'Rehmat Ali','Sarfraz Ahmed','Shaukat Hussain',
    'Shoaib Ahmed','Tariq Mehmood','Waqar Ahmed',
    'Waseem Ahmed','Yasir Mehmood','Younis Ahmed',
    'Zahid Hussain','Zameer Ahmed','Zubair Ahmed',
]

PAKISTANI_AREAS = [
    'F-5','F-6','F-6/1','F-6/2','F-6/3','F-6/4',
    'F-7','F-7/1','F-7/2','F-7/3','F-7/4',
    'F-8','F-8/1','F-8/2','F-8/3','F-8/4',
    'F-10','F-10/1','F-10/2','F-10/3','F-10/4',
    'F-11','F-11/1','F-11/2','F-11/3','F-11/4',
    'G-5','G-6','G-6/1','G-6/2','G-6/3','G-6/4',
    'G-7','G-7/1','G-7/2','G-7/3','G-7/4',
    'G-8','G-8/1','G-8/2','G-8/3','G-8/4',
    'G-9','G-9/1','G-9/2','G-9/3','G-9/4',
    'G-10','G-10/1','G-10/2','G-10/3','G-10/4',
    'G-11','G-11/1','G-11/2','G-11/3','G-11/4',
    'G-13','G-13/1','G-13/2','G-13/3','G-13/4',
    'G-14','G-14/1','G-14/2','G-14/3','G-14/4',
    'G-15','G-15/1','G-15/2','G-15/3','G-15/4',
    'H-8','H-9','H-10','H-11','H-12',
    'I-8','I-8/1','I-8/2','I-8/3','I-8/4',
    'I-9','I-9/1','I-9/2','I-9/3','I-9/4',
    'I-10','I-10/1','I-10/2','I-10/3','I-10/4',
    'I-11','I-11/1','I-11/2','I-11/3','I-11/4',
    'I-12','I-14','I-15','I-16',
    'D-12','E-7','E-8',
    'Blue Area','Bahria Enclave','Naval Anchorage','Park View City',
    'Capital Smart City','Gulberg Greens','Gulberg Residencia',
    'PWD Housing Society','Soan Garden','Pakistan Town',
    'Media Town','Korang Town','Alipur Farash',
    'Bhara Kahu','Bani Gala','Chak Shahzad',
    'Nilore','Taramri','Koral','Rawat','Lehtrar Road',
    'Satellite Town','Commercial Market','6th Road',
    'Committee Chowk','Chandni Chowk','Rehmanabad','Shamsabad',
    'Saddar Rawalpindi','Mall Road','Murree Road',
    'Liaquat Bagh','Asghar Mall','Sarafa Bazaar',
    'Ratta Amral','Pirwadhai','Dhoke Kala Khan',
    'Dhoke Hassu','Dhoke Syedan','Dhoke Awan',
    'Dhoke Chaudhrian','Afshan Colony',
    'Gulshanabad','Gulraiz','Race Course',
    'Khayaban-e-Sir Syed','Westridge 1','Westridge 2','Westridge 3',
    'Chaklala Scheme 1','Chaklala Scheme 2',
    'Tench Bhatta','Lalazar','Adiala Road',
    'Dhamial','Airport Housing Society',
    'Rawalpindi Cantt','Hyder Road','Adamjee Road',
    'Tipu Road','Kashmir Road','Mall Road Cantt',
    'King Road','Tariqabad','Model Town',
    'Mecca Chowk','Sahara Colony',
    'Chakri Road','Sahala','Bhangali',
    'Rawat','Mandra','G.T. Road Rawalpindi',
    'Bahria Town Phase 1','Bahria Town Phase 2',
    'Bahria Town Phase 3','Bahria Town Phase 4',
    'Bahria Town Phase 5','Bahria Town Phase 6',
    'Bahria Town Phase 7','Bahria Town Phase 8',
    'DHA Phase 1','DHA Phase 2','DHA Phase 3',
    'DHA Phase 4','DHA Phase 5',
    'Attock City','Attock Cantt','Campbellpur',
    'Hazro','Fateh Jang','Pindigheb',
    'Jand','Hasan Abdal','Basal',
    'Kamra','Burhan','Ghazi',
    'Shamsabad Attock','Mehfooz Shaheed Colony',
    'Taxila','Wah Cantt','Lal Rukh',
    'Wah Model Town','Mohra Shah Wali Shah',
    'New City Wah','Heavy Mechanical Complex',
    'University of Engineering and Technology Taxila',
    'Gujar Khan City','Gulyana','Bewal',
    'Daultala','Sohawa','Islampura',
    'Mandra','Jatli','Kotli Sattian',
    'Jhelum City','Jhelum Cantt','Dina',
    'Sarai Alamgir','Khewra',
    'New Jhelum City','Pind Dadan Khan',
    'Lilla','Jalalpur Sharif',
    'Chakwal City','Talagang','Dhudial',
    'Choa Saidan Shah','Kallar Kahar',
    'Katas Raj','Kot Sarang',
    'Pind Dadan Khan (Chakwal side)',
]

DISTRICTS = ['ISLAMABAD', 'RAWALPINDI', 'ATTOCK', 'JHELUM', 'CHAKWAL']

PDF_AREAS = ['BAHRIA TOWN', 'DHA', 'GULBERG', 'F-6', 'F-7', 'F-8', 'G-6', 'G-7']

SUB_DIVISIONS = {
    'ISLAMABAD': [
        'F-5','F-6','F-7','F-8','F-10','F-11',
        'G-5','G-6','G-7','G-8','G-9','G-10','G-11','G-13','G-14','G-15',
        'H-8','H-9','H-10','H-11','H-12',
        'I-8','I-9','I-10','I-11','I-12','I-14','I-16',
        'BARAKAHU','BHARA KAHU','BANI GALA','CHAK SHAHZAD','KORAL',
        'TARAMRI','NILORE','LEHTRAR ROAD','SOAN GARDEN','PWD',
        'KORANG TOWN','PAKISTAN TOWN','GULBERG GREENS','BAHRIA ENCLAVE'
    ],
    'RAWALPINDI': [
        'SADDAR','CANTT','SATELLITE TOWN','WESTRIDGE','CHAKLALA',
        'RACE COURSE','GULRAIZ','TENCH BHATTA','LALAZAR','PIRWADHAI',
        'RATTA AMRAL','ASGHAR MALL','ADIALA ROAD','QAYYUMABAD','DHOKE KALA KHAN',
        'RAWAT','MANDRA','KAHUTA','GUJAR KHAN','TAXILA (RP SIDE)','MURREE'
    ],
    'ATTOCK': [
        'ATTOCK CITY','ATTOCK CANTT','HASSAN ABDAL','TAXILA','WAH CANTT',
        'HAZRO','FATEH JANG','PINDIGHEB','JAND','KAMRA','BASAL','BURHAN','GHORGHUSHTI'
    ],
    'JHELUM': [
        'JHELUM CITY','JHELUM CANTT','DINA','SARAI ALAMGIR','PIND DADAN KHAN','SOHAWA'
    ],
    'CHAKWAL': [
        'CHAKWAL CITY','TALAGANG','CHOA SAIDAN SHAH','KALLAR KAHAR',
        'DHUDIAL','LILLA','BALKASSAR','LAWA'
    ]
}

FEEDER_NAMES = [
    '061101 CANTT','061102 SADDAR','061103 SATELLITE TOWN','061104 WESTRIDGE',
    '061105 CHAKLALA','061106 QAYYUMABAD','061107 GULRAIZ','061108 TENCH BHATTA',
    '061109 LALAZAR','061110 RACE COURSE','061111 PIRWADHAI','061112 RATTA AMRAL',
    '061113 ASGHAR MALL','061114 ADIALA ROAD','061115 DHOKE KALA KHAN',
    '061116 QAYYUMABAD','061117 WESTRIDGE','061118 SATELLITE TOWN','061119 CHAKLALA',
    '061120 GULBERG','061121 BAHRIA TOWN PHASE 1','061122 BAHRIA TOWN PHASE 2',
    '061123 BAHRIA TOWN PHASE 3','061124 BAHRIA TOWN PHASE 4','061125 BAHRIA TOWN PHASE 5',
    '061126 BAHRIA TOWN PHASE 6','061127 BAHRIA TOWN PHASE 7','061128 BAHRIA TOWN PHASE 8',
    '061129 DHA PHASE 1','061130 DHA PHASE 2','061131 DHA PHASE 3','061132 DHA PHASE 4',
    '061133 DHA PHASE 5','061134 RAWAT','061135 MANDRA','061136 KAHUTA ROAD',
    '061137 AIRPORT HOUSING','061138 PWD RAWALPINDI SIDE',
    '062101 F-6','062102 F-7','062103 F-8','062104 F-10','062105 F-11',
    '062106 G-6','062107 G-7','062108 G-8','062109 G-9','062110 G-10',
    '062111 G-11','062112 G-13','062113 G-14','062114 G-15','062115 I-8',
    '062116 I-9','062117 I-10','062118 I-11','062119 I-12','062120 I-14',
    '062121 H-8','062122 H-9','062123 BARAKAHU','062124 BHARA KAHU','062125 BANI GALA',
    '062126 CHAK SHAHZAD','062127 KORAL','062128 TARAMRI','062129 NILORE',
    '062130 SOAN GARDEN','062131 PWD ISLAMABAD','062132 KORANG TOWN',
    '062133 PAKISTAN TOWN','062134 GULBERG GREENS','062135 BAHRIA ENCLAVE',
    '063101 ATTOCK CITY','063102 ATTOCK CANTT','063103 HASSAN ABDAL','063104 TAXILA',
    '063105 WAH CANTT','063106 HAZRO','063107 FATEH JANG','063108 PINDIGHEB',
    '063109 JAND','063110 KAMRA','063111 BASAL','063112 BURHAN','063113 GHORGHUSHTI',
    '064101 JHELUM CITY','064102 JHELUM CANTT','064103 DINA','064104 SARAI ALAMGIR',
    '064105 PIND DADAN KHAN','064106 SOHAWA','064107 LILLA JHELUM','064108 NEW JHELUM',
    '065101 CHAKWAL CITY','065102 TALAGANG','065103 CHOA SAIDAN SHAH','065104 KALLAR KAHAR',
    '065105 DHUDIAL','065106 LILLA','065107 BALKASSAR','065108 LAWA'
]

IESCO_TARIFF_DETAILS = {
    'A-1a(01)': {
        'name': 'Residential Protected',
        'rates': [(50, 2.0), (100, 5.79), (200, 8.11), (300, 10.20), (700, 17.60), (float('inf'), 20.0)],
        'meter_rent': 18.06,
        'service_rent': 13.85,
        'gst_rate': 0.17
    },
    'A-1a(02)': {
        'name': 'Residential General',
        'rates': [(50, 2.0), (100, 5.79), (200, 8.11), (300, 10.20), (700, 17.60), (float('inf'), 20.0)],
        'meter_rent': 18.06,
        'service_rent': 13.85,
        'gst_rate': 0.17
    },
    'A-1b(01)': {
        'name': 'Residential Commercial',
        'rates': [(float('inf'), 20.0)],
        'meter_rent': 25.00,
        'service_rent': 15.50,
        'gst_rate': 0.17
    },
    'A-2a(01)': {
        'name': 'Commercial Small',
        'rates': [(float('inf'), 18.0)],
        'meter_rent': 30.00,
        'service_rent': 18.00,
        'gst_rate': 0.17
    },
    'B-1(01)': {
        'name': 'Industrial Small',
        'rates': [(float('inf'), 16.0)],
        'meter_rent': 50.00,
        'service_rent': 25.00,
        'gst_rate': 0.17
    }
}

MONTH_NAMES = ['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC']

PAYMENT_BEHAVIORS = {
    'prompt_payer': {'prob': 0.25, 'late_prob': 0.05, 'partial_prob': 0.02, 'installment_prob': 0.01, 'default_prob': 0.0},
    'regular_payer': {'prob': 0.35, 'late_prob': 0.15, 'partial_prob': 0.05, 'installment_prob': 0.03, 'default_prob': 0.02},
    'late_payer': {'prob': 0.20, 'late_prob': 0.40, 'partial_prob': 0.10, 'installment_prob': 0.05, 'default_prob': 0.05},
    'irregular_payer': {'prob': 0.12, 'late_prob': 0.30, 'partial_prob': 0.20, 'installment_prob': 0.10, 'default_prob': 0.15, 'disconnect_prob': 0.20},
    'defaulter': {'prob': 0.08, 'late_prob': 0.20, 'partial_prob': 0.30, 'installment_prob': 0.15, 'default_prob': 0.35, 'disconnect_prob': 0.50}
}
